export const FETCH_POSTS = 'POST/FETCH_POSTS'
export const CHANGE_LOAD_VALUE = 'POST/CHANGE_LOAD_VALUE'
export const REQUEST_POSTS = 'POST/REQUEST_POSTS'
export const CHANGE_START_VALUE = 'POST/CHANGE_START_VALUE'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const CHANGE_THEME = 'APP/CHANGE_THEME'
export const IS_MODAL_OPEN = 'APP/IS_MODAL_OPEN'

export const RESET = 'APP/RESET'
